language: php
php:
  - 5.4
  - 5.5
notifications:
  irc:
    use_notice: true
    skip_join: true
    channels: ["irc.freenode.org#imbo"]

before_script:
  - composer self-update
  - composer -n --dev install --prefer-source

script:
  - ./vendor/bin/phpunit -c tests
